// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ekhvalov/otus-banners-rotation/internal/app (interfaces: Rotator)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRotator is a mock of Rotator interface.
type MockRotator struct {
	ctrl     *gomock.Controller
	recorder *MockRotatorMockRecorder
}

// MockRotatorMockRecorder is the mock recorder for MockRotator.
type MockRotatorMockRecorder struct {
	mock *MockRotator
}

// NewMockRotator creates a new mock instance.
func NewMockRotator(ctrl *gomock.Controller) *MockRotator {
	mock := &MockRotator{ctrl: ctrl}
	mock.recorder = &MockRotatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRotator) EXPECT() *MockRotatorMockRecorder {
	return m.recorder
}

// AttachBanner mocks base method.
func (m *MockRotator) AttachBanner(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachBanner", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachBanner indicates an expected call of AttachBanner.
func (mr *MockRotatorMockRecorder) AttachBanner(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachBanner", reflect.TypeOf((*MockRotator)(nil).AttachBanner), arg0, arg1, arg2)
}

// ClickBanner mocks base method.
func (m *MockRotator) ClickBanner(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClickBanner", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClickBanner indicates an expected call of ClickBanner.
func (mr *MockRotatorMockRecorder) ClickBanner(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClickBanner", reflect.TypeOf((*MockRotator)(nil).ClickBanner), arg0, arg1, arg2, arg3)
}

// CreateBanner mocks base method.
func (m *MockRotator) CreateBanner(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBanner", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBanner indicates an expected call of CreateBanner.
func (mr *MockRotatorMockRecorder) CreateBanner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBanner", reflect.TypeOf((*MockRotator)(nil).CreateBanner), arg0, arg1)
}

// CreateSlot mocks base method.
func (m *MockRotator) CreateSlot(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlot", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSlot indicates an expected call of CreateSlot.
func (mr *MockRotatorMockRecorder) CreateSlot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlot", reflect.TypeOf((*MockRotator)(nil).CreateSlot), arg0, arg1)
}

// CreateSocialGroup mocks base method.
func (m *MockRotator) CreateSocialGroup(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSocialGroup", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSocialGroup indicates an expected call of CreateSocialGroup.
func (mr *MockRotatorMockRecorder) CreateSocialGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSocialGroup", reflect.TypeOf((*MockRotator)(nil).CreateSocialGroup), arg0, arg1)
}

// DeleteBanner mocks base method.
func (m *MockRotator) DeleteBanner(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBanner", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBanner indicates an expected call of DeleteBanner.
func (mr *MockRotatorMockRecorder) DeleteBanner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBanner", reflect.TypeOf((*MockRotator)(nil).DeleteBanner), arg0, arg1)
}

// DeleteSlot mocks base method.
func (m *MockRotator) DeleteSlot(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSlot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSlot indicates an expected call of DeleteSlot.
func (mr *MockRotatorMockRecorder) DeleteSlot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSlot", reflect.TypeOf((*MockRotator)(nil).DeleteSlot), arg0, arg1)
}

// DeleteSocialGroup mocks base method.
func (m *MockRotator) DeleteSocialGroup(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSocialGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSocialGroup indicates an expected call of DeleteSocialGroup.
func (mr *MockRotatorMockRecorder) DeleteSocialGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSocialGroup", reflect.TypeOf((*MockRotator)(nil).DeleteSocialGroup), arg0, arg1)
}

// DetachBanner mocks base method.
func (m *MockRotator) DetachBanner(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachBanner", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachBanner indicates an expected call of DetachBanner.
func (mr *MockRotatorMockRecorder) DetachBanner(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachBanner", reflect.TypeOf((*MockRotator)(nil).DetachBanner), arg0, arg1, arg2)
}

// SelectBanner mocks base method.
func (m *MockRotator) SelectBanner(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBanner", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBanner indicates an expected call of SelectBanner.
func (mr *MockRotatorMockRecorder) SelectBanner(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBanner", reflect.TypeOf((*MockRotator)(nil).SelectBanner), arg0, arg1, arg2)
}
