version: "3.8"
services:
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis:/data

  rotator:
    image: otus-golang/rotator:develop

  tester:
    image: golang:1.19.3
    working_dir: /usr/src/rotator
    volumes:
      - ../..:/usr/src/rotator
    environment:
      TESTS_GRPC_SERVER_HOST: rotator
    depends_on:
      - redis
      - rotator
    command: [ "go", "test", "-v", "-tags=integration", "./internal/tests/integration/..."]

volumes:
  redis:
