name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Run redis container
        run: docker run --rm -d --publish 127.0.0.1:6379:6379 --name redis redis:7.0-alpine

      - name: Wait for redis is up
        run: sleep 5

      - name: Test redis storage
        run: go test -v -tags=integration ./internal/environment/storage/redis/...

      - name: Remove redis container
        run: docker container rm --force redis

  test-integration:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run redis container
        run: docker run --rm -d --publish 127.0.0.1:6379:6379 --network host --name redis redis:7.0-alpine

      - name: Run rabbitmq container
        run: docker run --rm -d --publish 127.0.0.1:5672:5672 --network host --name rabbitmq rabbitmq:3.11-alpine

      - name: Build rotator container
        run: make build-img

      - name: Run rotator container
        run: docker run --rm -d
          --publish 127.0.0.1:8081:8081
          --network host
          --env ROTATOR_REDIS_HOST=localhost
          --env ROTATOR_RABBITMQ_HOST=localhost
          --name rotator
          otus-golang/rotator:develop

      - name: Run tests
        run: go test -v -tags=integration ./internal/tests/integration/...

      - name: Remove redis container
        run: docker container rm --force redis

      - name: Remove rabbitmq container
        run: docker container rm --force rabbitmq

      - name: Remove rotator container
        run: docker container rm --force rotator
